### ISSUE TITLE
OS and Uptime improvement

### ISSUE THREAD

**Issue by q60** [KikyTokamuro/fetch.scm#1]
# The issues

greetings! here's some issues with the code i am not capable of fixing myself :pleading_face: 

## OS
https://github.com/KikyTokamuro/fetch.scm/blob/0ff8769a67a479adec569018a869acc898a019a6/fetch.scm#L42

`/etc/os-release` is not a cross-distro file

## Uptime

https://github.com/KikyTokamuro/fetch.scm/blob/0ff8769a67a479adec569018a869acc898a019a6/fetch.scm#L28

`/proc/uptime` doesn't exist in every OS too

## My suggestion

i am sorry, i am not a Schemer, so, unfortunately, i can't do a thing myself. but you may have a look at [disfetch](https://github.com/q60/disfetch). uptime layer may seem a little tricky and frustrating, but i think you can handle it better in Scheme than me in Bash. OS though is pretty simple. paç fat! :smile:

**Comment by KikyTokamuro** [comment]
Hey @q60! Thanks for the issue ;)

65cfc8e - Fixed getting the name of the distro:
- /etc/os-release
- /usr/lib/os-release
- lsb_release -sd
- uname -o

229331c - Fixed getting the uptime:
- /proc/uptime
- uptime -p

In the future, I will add an option that does not fall under any of the above.

At the moment, these changes solve the shortcomings you mentioned?

**Comment by q60** [comment]
sure they do. but `/etc/os-release` is a symbolic link to `/usr/lib/os-release`, so there's no need in checking both of them

**Comment by KikyTokamuro** [comment]
Okay, thanks for the advice, I'll change.

Could you provide a screenshot of the work so that I can be sure that everything works fine?

The initial launch will compile the script and there will be an extra exhaust of unnecessary information (this, unfortunately, cannot be disabled in the guile), but it will not be present on next launches.

**Comment by q60** [comment]
![image](https://user-images.githubusercontent.com/61933599/129751130-5ee291d2-43fb-4643-bdf3-25e4cc8d7975.png)
