### ISSUE TITLE
hardware model

### ISSUE THREAD

**Issue by q60** [KikyTokamuro/fetch.scm#4]
can you, please, exclude `model` layer if such things appear? cuz i have a pc

![image](https://user-images.githubusercontent.com/61933599/131388998-20debabc-cf0f-4a40-82f0-ef6d65921336.png)

**Comment by KikyTokamuro** [comment]
What options for checking this case can you suggest?
Can be checked for the phrase "To Be Filled By O.E.M." ?

**Comment by q60** [comment]
> What options for checking this case can you suggest?
> Can be checked for the phrase "To Be Filled By O.E.M." ?

yeah

**Comment by KikyTokamuro** [comment]
Please check this commit, is it working properly for you now? 3d8c254

**Comment by q60** [comment]
It would be better if model line won't show up at all

**Comment by q60** [comment]
I mean if it's unknown

**Comment by q60** [comment]
Sorry, I am feeling sick, so I can't update AUR package right now, I'll go sleep then update it in the morning

**Comment by KikyTokamuro** [comment]
In one of the releases, I will definitely add a check for "unknown". For now, let it stay like this :)

**Comment by KikyTokamuro** [comment]
Do not be ill, a speedy recovery for you!

**Comment by q60** [comment]
Thanks! Farewell and good night

**Comment by q60** [comment]
<img align="left" width="40%" src="https://user-images.githubusercontent.com/61933599/131466308-94a7dc40-9120-4f35-afaa-05f98c1739c2.png">

ok, i am here now and we can continue. there's no actual need in changing versioning after updates. please, roll back to 0.1.4

why no need? we already have a thing like `pkgrel` in AUR's PKGBUILD. change back to x.x.x versioning, delete these two releases and their respective version tags.  then create a new updated v0.1.4 release.

**Comment by q60** [comment]
@KikyTokamuro

**Comment by KikyTokamuro** [comment]
@q60 All is ready :)

**Comment by q60** [comment]
done, i've updated AUR package
